apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-svc
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app-name: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
